### ISSUE TITLE
Package not installing with npm

### ISSUE THREAD

**Issue by SeunMatt** [hokein/node-minizip#8]
The package refuse to install with npm install command
npm version 2.1.42

**Comment by hokein** [comment]
@SeunMatt could you paste the error message of the `npm install` command and provide your OS?
I can install the package via `npm install` on MacOS with `npm 3.10.3`.

**Comment by SeunMatt** [comment]
This is the error message
my OS is Windows 8.1

 λ npm install -g node-minizip  
|                                                                                                     

> node-minizip@0.3.0 install C:\Users\smatt\AppData\Roaming\npm\node_modules\node-minizip  
> node-gyp rebuild                                                                                    

C:\Users\smatt\AppData\Roaming\npm\node_modules\node-minizip>if not defined npm_config_node_gyp (node 
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )  else (node  rebuild )  
gyp ERR! configure error  
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.  
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib
\configure.js:116:14)  
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:
71:11  
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)  
gyp ERR! System Windows_NT 6.3.9600  
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\
node_modules\node-gyp\bin\node-gyp.js" "rebuild"  
gyp ERR! cwd C:\Users\smatt\AppData\Roaming\npm\node_modules\node-minizip  
gyp ERR! node -v v4.3.0  
gyp ERR! node-gyp -v v3.0.3  
gyp ERR! not ok  
npm ERR! Windows_NT 6.3.9600  
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin
\npm-cli.js" "install" "-g" "node-minizip"  
npm ERR! node v4.3.0  
npm ERR! npm  v2.14.12  
npm ERR! code ELIFECYCLE                                                                              

npm ERR! node-minizip@0.3.0 install: `node-gyp rebuild`  
npm ERR! Exit status 1  
npm ERR!  
npm ERR! Failed at the node-minizip@0.3.0 install script 'node-gyp rebuild'.  
npm ERR! This is most likely a problem with the node-minizip package,  
npm ERR! not with npm itself.  
npm ERR! Tell the author that this fails on your system:  
npm ERR!     node-gyp rebuild  
npm ERR! You can get their info via:  
npm ERR!     npm owner ls node-minizip  
npm ERR! There is likely additional logging output above.                                             

npm ERR! Please include the following file with any support request:  
npm ERR!     C:\Users\smatt\npm-debug.log

**Comment by hokein** [comment]
From the log messages, you are missing python, which is one of the prerequisites build node native addon. You need to install python 2.7 on your machine.
